### ISSUE TITLE
Tiles randomly disappear when played in PowerShell

### ISSUE THREAD

**Issue by moigagoo** [bfontaine/term2048#24]
When two tiles are paired into one, a tile may disappear completely from the field.

Reproduced on PowerShell in every game.

Cmd works all right though.

**Comment by pawulon** [comment]
Powershell doesn't display magenta on a default background.
[default shortcut on Windows remaps ANSI colors 35,36](https://github.com/PowerShell/PowerShell/issues/4266)
Workaround - change background color to black.

**Comment by bfontaine** [comment]
Thanks a lot @pawulon!

> Workaround - change background color to black.

Alternatively, we could change the colors not to use magenta.

**Comment by pawulon** [comment]
Yes. I did a test with:
1. **Fore.LIGHTMAGENTA_EX** instead of **Fore.MAGENTA**
2. **Fore.MAGENTA + Style.BRIGHT** instead of **Fore.MAGENTA**

and it worked good in three command line tools on Windows (cmd.exe, powershell, cmder).

Also, powershell displays yellow color as white. It is not a big problem since the tile is not disappearing but we may also apply potential fix to it.
